### PR TITLE
Fixing addQJets

### PR DESCRIPTION
**Pull request by mhwalker**
The current code adds an incorrectly named user variable, which throws a ProductNotFound exception. I changed it to match the correct name.

### CODE REVIEW

**Comment by rappoccio** [comment]
What release/releases is this compatible with?

**Comment by alefisico** [comment]
I think actually it must be something like in the case of PUJetID: https://github.com/mhwalker/JetToolbox/blob/0873adde5a1c0490912f599b9babb2b452fe8053/python/jetToolbox_cff.py#L714-L732
because otherwise there will not be difference if you want to run Puppi or CHS or other PUMethod.

**Comment by rappoccio** [comment]
OK, what is the recipe to be consistent? Is this PR synced to the JetToolbox?

**Comment by ahinzmann** [comment]
It looks like the q/g-discrimination code is under "addQJets". QJets (for W-tagging) and QG-likelihood are completely different discriminators.

**Comment by mhwalker** [comment]
The change I made works in CMSSW_7_4_2. Based on the surrounding comments in the code, I guess it won't work in 73X, though I didn't test it.

**Comment by alefisico** [comment]
I think we will have the issue as with PUJetID with the names for Puppi or CHS. Let me fix this (changing it to QGJets too) and I will make a new pull request

**Comment by rappoccio** [comment]
Thanks @alefisico. Can you do the jetToolbox and this together? 

We're going to need to make a specific tag for this in both of the cases so that we can ensure people are using the right thing, since they can now get out of sync.

**Comment by alefisico** [comment]
@rappoccio sorry, what do you mean by do the jetToolbox and this together?

**Comment by rappoccio** [comment]
Wait, never mind. I misread this and thought it was part of the JMEValidator. 

OK, sorry for the confusion! :)

**Comment by alefisico** [comment]
I just fix the QGtagger part in another pull: https://github.com/cms-jet/JetToolbox/pull/15
Therefore I will close this pull.

**Pull request closed without merging**
