### PR TITLE
Jet toolbox 74 x

### PR DESCRIPTION
**Pull request by jbrands**
jetToolbox with PU

### CODE REVIEW

**Comment by ahinzmann** [comment]
this pull request looks good to me. Any problem?

**Comment by jbrands** [comment]
I just wanted that only the last commit is shown, because it contains all changes.

**Comment by alefisico** [comment]
just please notice that the master branch is still for 73X and this change is for 74X. I leave the master for 73X because it is a non-changing version, but we can update it too if you think is fine.

**Comment by ahinzmann** [comment]
The diff looks good, and the merging of 4 commits is just (difficult) cosmetics.
@alefisico: You're the master of this code, so you click merge :-)

**Pull request merged**
